[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/checkout"
  to = "/.netlify/functions/checkout"
  status = 302

[[redirects]]
  from = "/finalize"
  to = "/.netlify/functions/finalize"
  status = 200

[[redirects]]
  from = "/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

[[redirects]]
  from = "/license"
  to = "/.netlify/functions/license"
  status = 200
